baskets:
  demo_small:
    - AAPL
    - MSFT
    - NVDA
    - AMZN
    - GOOGL
    - META
    - BRK-B
    - JPM
    - V
    - WMT
    - AMD
    - CRM
    - UBER
    - CRWD
    - SNOW
    - SOFI
    - BRK-A
    - CELH
    - ^DJI
    - ^IXIC

    - BTC-USD
    - ETH-USD
    - SOL-USD
    - BNB-USD
    - XRP-USD
    - ADA-USD
    - DOGE-USD
    - LINK-USD